import fs from 'node:fs'
import path from 'node:path'
import { compileFromFile } from 'json-schema-to-typescript'
import openapiTS, { astToString } from 'openapi-typescript'

const banner: string = `
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
`

const openapiTsBanner: string = `
/* eslint-disable */
/**
 * This file was automatically generated from OpenAPI specification.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI spec,
 * and regenerate this file.
 */
`

const middleLayerPath = '../impresso-middle-layer'

const basePath: string = `${middleLayerPath}/src/schema`
const outputPath: string = './src/models/generated'
const schemaBits: string[] = ['schemas', 'schemas/contentItem', 'schemasPublic']

const directories = fs
  .readdirSync(basePath, {
    recursive: true
  })
  .filter((item: string) => {
    const s = fs.statSync(`${basePath}/${item}`)
    return s.isDirectory()
  })
  .filter((item: string) => schemaBits.includes(item)) as string[]

async function compileDirectory(
  basePath: string,
  dir: string,
  outputBasePath: string
): Promise<void> {
  const dirPath: string = `${basePath}/${dir}`

  const files: string[] = fs.readdirSync(dirPath).filter((item: string) => {
    const path = `${dirPath}/${item}`
    const isDir = fs.statSync(path).isDirectory()
    return !isDir
  })
  // eslint-disable-next-line no-console
  console.log(`${files.length} files in ${dir}:`)

  const tsContents: string[] = await Promise.all(
    files.map((fileName: string) => {
      const inputFile = `${dirPath}/${fileName}`
      return compileFromFile(inputFile, {
        bannerComment: ''
      })
    })
  )

  const content: string = [banner, ...tsContents].join('\n\n')
  const outputFile: string = `${outputBasePath}/${dir}.d.ts`
  fs.writeFileSync(outputFile, content)
}

async function compileAll(
  basePath: string,
  outputPath: string,
  directories: string[]
): Promise<void> {
  for (const dir of directories) {
    // eslint-disable-next-line no-console
    console.log(`Generating types for group ${dir}...`)
    await compileDirectory(basePath, dir, outputPath)
  }
}

async function generateBaristaTypes(): Promise<void> {
  const baristaUrl = 'http://0.0.0.0:8042/openapi.json'
  const outputDir = './src/models/generated/barista'
  const outputFile = path.join(outputDir, 'schema.d.ts')

  // eslint-disable-next-line no-console
  console.log('Generating types from Barista OpenAPI spec...')

  try {
    // Fetch the OpenAPI spec
    const response = await fetch(baristaUrl)
    if (!response.ok) {
      throw new Error(`Failed to fetch OpenAPI spec: ${response.statusText}`)
    }
    const openapiSpec = await response.json()

    // Create output directory if it doesn't exist
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    // Use openapi-typescript to generate types
    const ast = await openapiTS(openapiSpec, {
      alphabetize: true,
      exportType: true
    })
    const typeContent = astToString(ast)

    // Write the types to file with banner
    const content = openapiTsBanner + '\n' + typeContent
    fs.writeFileSync(outputFile, content)

    // eslint-disable-next-line no-console
    console.log(`✓ Generated Barista types at ${outputFile}`)
  } catch (error) {
    // eslint-disable-next-line no-console
    console.warn(
      '⚠ Could not generate Barista types (service may not be running):',
      error instanceof Error ? error.message : error
    )
  }
}

async function generateAllTypes(): Promise<void> {
  // Generate middle-layer types
  await compileAll(basePath, outputPath, directories)

  // Generate Barista types
  await generateBaristaTypes()
}

generateAllTypes()
  .then(() => {
    // eslint-disable-next-line no-console
    console.log('Done')
  })
  .catch((e: Error) => console.error(e))
