<template>
  <div class="TroublesAhead px-3 py-2 d-flex flex-column" style="transform:translateY(-3000px)" v-if="!dulyNoted">
    <header>
      <h1 >Scheduled Maintenance and possible interruptions</h1>
    </header>
    <main class="my-2">
      <p >
        The impresso app will be undergoing maintenance from 14 June 2023. Expect disruptions, slow loading, or temporary unavailability of features. We apologize for any inconvenience. For assistance, reach us at <a href="mailto:info@impresso-project.ch" target="_blank">info@impresso-project.ch</a>.
    </p>
    </main>
    <footer>
      <button class="btn btn-secondary rounded shadow-sm btn-sm btn-block" v-on:click="noted">noted, don't display again.</button>
    </footer>
  </div>
</template>

<script>
export default {
  data () {
    return {
      bufferDulyNoted: false
    }
  },
  name: 'TroublesAhead',
  // on mounted, fade in the modal
  mounted() {
    setTimeout(() => {
      this.$el.style.opacity = 1;
      // transform scale, with wobble effect
      this.$el.classList.add('animated');
    }, 1000);
  },
  methods: {
    noted() {
      console.info('accepting disclaimer')
      this.bufferDulyNoted = true;
      // set the value in localstorage
      localStorage.setItem('dulyNoted', true);
    },
  },
  computed: {
    dulyNoted() {
      // get the value from localstorage
      if (this.bufferDulyNoted) {
        return true;
      }
      return localStorage.getItem('dulyNoted') !== null;
    },
  },
};
</script>

<style lang="css">
.TroublesAhead {
  border: 1px solid;
  position: fixed;
  top: 50%;
  left: 50%;
  width: 400px;
  margin-left: -150px;
  margin-top: -100px;
  pointer-events: auto;
  background: #FFEB78;
  border-radius: 4px;
  will-change: opacity, transform;
  transition: opacity 0.3s ease-in-out, transform 0.3s ease-in-out;
  box-shadow: rgba(190, 185, 35, 0.22) 0px 7px 29px 0px;;
  animation-duration: 2s;
  animation-fill-mode: both;
}

.TroublesAhead main {
  flex: 1;
}

.TroublesAhead h1{
  font-size: 1.75em;
}
.TroublesAhead.animated {
  -webkit-animation: slide-in-blurred-top 0.6s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
  animation: slide-in-blurred-top 0.6s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-6-13 13:48:58
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-top
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-blurred-top {
  0% {
    -webkit-transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
            transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    -webkit-filter: blur(40px);
            filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
            transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-top {
  0% {
    -webkit-transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
            transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    -webkit-filter: blur(40px);
            filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
            transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}


</style>
